name: kepleomax
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  dio: ^5.9.0
  email_validator: ^3.0.0
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  freezed_annotation: 3.1.0
  json_annotation: ^4.9.0
  jwt_decoder: ^2.0.1
  logger: ^2.6.2
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.9.0
  retrofit_generator: ^10.0.6
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.10.1
  freezed: ^3.2.3
  json_serializable: ^6.11.1

flutter:
  uses-material-design: true
