name: kepleomax
description: "Kepleomax is Leonid's pet project"
publish_to: 'none'
version: 0.1.4

environment:
  sdk: ^3.9.0

dependencies:
  bloc_concurrency: ^0.3.0
  cached_network_image: ^3.4.1
  collection: ^1.19.1
  dio: ^5.9.0
  email_validator: ^3.0.0
  firebase_analytics: ^12.0.4
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_local_notifications: ^19.5.0
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.2.2
  fluttertoast: ^9.0.0
  focus_detector: ^2.0.1
  freezed_annotation: 3.1.0
  gal: ^2.3.2
  image: ^4.5.4
  image_picker: ^1.2.0
  images_keys: ^0.0.4
  intl: ^0.20.2
  json_annotation: ^4.9.0
  jwt_decoder: ^2.0.1
  logger: ^2.6.2
  ntp: ^2.0.0
  num_remap: ^1.0.2
  path_provider: ^2.1.5
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.9.0
  retrofit_generator: ^10.0.6
  rxdart: ^0.28.0
  scroll_to_index: ^3.0.1
  shared_preferences: ^2.5.3
  skeletonizer: ^2.1.0+1
  socket_io_client: ^3.1.2
  sqflite: ^2.4.2
  synchronized: ^3.4.0
  web_socket_channel: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.10.1
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
